#!/bin/bash

if [ -z "$POETRY_ACTIVE" ]
then
	echo "entering project virtual enviroment"
	source $(poetry env info --path)/bin/activate
fi


if [ ! -e "./swam.py" ]; then
    echo "initializing swamcore"
    git submodule init
    git submodule update
fi

./swam.py -w -s
