#!/bin/bash

if [ -z "$POETRY_ACTIVE" ]
then
	echo "entering project virtual enviroment"
	source $(poetry env info --path)/bin/activate
fi


if [ ! -e "./swam.py" ]; then
    echo "initializing swamcore"
    git submodule init
    git submodule update
fi

# run once to build with no versioning
./swam.py
# run again to build with versioning
./swam.py -w -s -a
